server:
  port: 8005
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka-server/eureka
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
logging:
  level: #修改日志级别
    com.thzy.openFeign.remote.UserRemoteService: debug
