server:
  port: 8003
  servlet:
    context-path: /eureka-server
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica1
  client:
    serviceUrl:
      defaultZone: http://replica2:8004/eureka-server/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: false
    register-with-eureka: false
