server:
  port: 8004
  servlet:
    context-path: /eureka-server
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    serviceUrl:
      defaultZone: http://replica1:8003/eureka-server/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: false
    register-with-eureka: false
